import turtle as trtl

painter = trtl.Turtle()

def makeSquare(size):
    for _ in range(4):
        painter.forward(size)
        painter.right(90)

def makePerson(scale):
    painter.begin_fill()
    painter.fillcolor("#c68642")
    painter.circle(scale*25)
    painter.end_fill()
    painter.left(90)
    painter.penup()
    painter.forward(scale*50)
    painter.pendown()
    painter.forward(scale*75)
    painter.left(45)
    painter.forward(scale*60)
    painter.back(scale*60)
    painter.right(90)
    painter.forward(scale*60)
    painter.back(scale*60)
    painter.right(135)
    painter.forward(scale*(75/2))
    painter.left(90)
    painter.forward(scale*30)
    painter.back(scale*30)
    painter.right(180)
    painter.forward(scale*30)
    painter.penup()
    painter.goto(0,0)
    painter.right(90)
    painter.forward(50)
    painter.goto(25,-50)
    painter.back(7)
    painter.right(90)
    painter.forward(3)
    painter.pendown()
    painter.begin_fill()
    painter.fillcolor("white")
    painter.circle(3)
    painter.end_fill()
    painter.penup()
    painter.left(90)
    painter.forward(3)
    painter.pendown()
    painter.begin_fill()
    painter.fillcolor("black")
    painter.circle(1)
    painter.penup()
    painter.back(3)
    painter.right(90)
    painter.back(10)
    painter.pendown()
    painter.begin_fill()
    painter.fillcolor("white")
    painter.circle(3)
    painter.end_fill()
    painter.penup()
    painter.left(90)
    painter.forward(3)
    painter.pendown()
    painter.begin_fill()
    painter.fillcolor("black")
    painter.circle(1)
    painter.penup()
    painter.forward(7)
    painter.right(90)
    painter.pendown()
    painter.forward(10)
    painter.penup()
    painter.goto(0,0)


painter.begin_fill()
painter.fillcolor("#bd952a")

makeSquare(100)

painter.end_fill()

painter.begin_fill()
painter.fillcolor("red")

painter.left(45)
painter.forward(75)
painter.right(90)
painter.forward(75)

painter.end_fill()


painter.penup()
painter.goto(25, -50)

painter.pendown()
painter.begin_fill()
painter.fillcolor("brown")
painter.right(45)
painter.forward(50)
painter.left(90)
painter.forward(40)
painter.left(90)
painter.forward(50)
painter.end_fill()

painter.penup()
painter.forward(15)
painter.pendown()

painter.begin_fill()
painter.fillcolor("lightblue")
makeSquare(20)
painter.end_fill()

painter.penup()
painter.left(90)
painter.forward(35)

painter.pendown()
painter.begin_fill()
painter.fillcolor("lightblue")
makeSquare(20)
painter.end_fill()

makePerson(1)



wn = trtl.Screen()
wn.mainloop()